micronaut:
  application:
    name: inventoryApiRestFull
  server:
    port: 8097
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/slplusdb2`}
    username: ${DB_USER:`root`}
    password: ${DB_PASS:`root`}
    driverClassName: com.mysql.cj.jdbc.Driver
    schema-generate: CREATE_DROP
    dialect: MYSQL
flyway:
  datasources:
    default:
      enabled: true