micronaut:
  application:
    name: inventoryApiRestFull
  server:
    port: 8097
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:mysql://localhost:3306/slplusdb2
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'root'
    schema-generate: CREATE_DROP
    dialect: MYSQL
flyway:
  datasources:
    default:
      enabled: true